train:
  weights: [1.0, 20.0]

data:
  fmeval: True
  low_rating_thres: ~
  binarized_rating_thres: ~
  split_mode: entry

eval:
  main_task: is_installed
  val_metrics: [logloss, auc, accuracy, f1, precision, recall]
  test_metrics: [logloss, auc, accuracy, f1, precision, recall]