model:
  num_experts: 4
  expert_mlp_layer: [128, 128]
  expert_activation: relu
  expert_dropout: 0.1
  expert_batch_norm: False

  gate_mlp_layer: [128, ]
  gate_activation: relu
  gate_dropout: 0.1
  gate_batch_norm: False

  tower_mlp_layer: [128, ]
  tower_activation: relu
  tower_dropout: 0.1
  tower_batch_norm: False

  reduction_ratio: 3
  excitation_activation: relu

  embed_dim: 64

train:
  weight_decay: 1e-5