model:
  embed_dim: 70
  combination: stacked
  low_rank: ~
  num_experts: 3
  num_layers: 4
  mlp_layer: [256, 256, 256]
  activation: relu
  cross_activation: tanh
  dropout: 0.1
  batch_norm: True

train:
  scheduler: exponential
  learning_rate: 1e-3
  weight_decay: 3e-5